import polars as pl, numpy as np
out=open("work/02_gt.txt","w")
def P(*a): print(*a,file=out,flush=True)
gt=pl.read_parquet("work/train_gt.parquet")
s1=pl.read_parquet("work/train_s1.parquet"); s2=pl.read_parquet("work/train_s2.parquet"); s3=pl.read_parquet("work/train_s3.parquet")
P("gt rows",gt.height,"unique s1",gt["source1_entity_id"].n_unique(), "s1 file rows", s1.height)
P("gt s1 ids not in S1:", gt.join(s1.select("entity_id"),left_on="source1_entity_id",right_on="entity_id",how="anti").height,
  " S1 not in gt:", s1.join(gt,left_on="entity_id",right_on="source1_entity_id",how="anti").height)
pairs=gt.with_columns(pl.col("matched_entity_ids").str.split(",")).explode("matched_entity_ids").filter(pl.col("matched_entity_ids")!="").rename({"source1_entity_id":"s1","matched_entity_ids":"m"})
pairs=pairs.filter(pl.col("m").is_not_null())
P("total pairs", pairs.height, " dup pairs:", pairs.height-pairs.unique().height, " malformed ids:", pairs.filter(~pl.col("m").str.contains(r"^S[23]-\d+$")).height)
pairs=pairs.with_columns(pl.col("m").str.slice(0,2).alias("src"))
P("pairs by src:", pairs["src"].value_counts().rows())
allm=pl.concat([s2.select("entity_id"),s3.select("entity_id")])
P("matched ids not in S2/S3:", pairs.join(allm,left_on="m",right_on="entity_id",how="anti").height)
mc=pairs.group_by("m").len()
P("S2/S3 ids matched to >1 S1:", mc.filter(pl.col("len")>1).height)
P("S2 records matched:", pairs.filter(pl.col("src")=="S2")["m"].n_unique(), "/", s2.height, " S3 matched:", pairs.filter(pl.col("src")=="S3")["m"].n_unique(),"/",s3.height)
per=pairs.group_by("s1").agg((pl.col("src")=="S2").sum().alias("n2"),(pl.col("src")=="S3").sum().alias("n3"))
per=s1.select(pl.col("entity_id").alias("s1"),"country").join(per,on="s1",how="left").fill_null(0).with_columns((pl.col("n2")+pl.col("n3")).alias("n"))
P("zero matches:", (per["n"]==0).sum(), f"{(per['n']==0).mean():.4f}")
P("n matches dist:", per["n"].value_counts().sort("n").rows())
P("n2 dist:", per["n2"].value_counts().sort("n2").rows())
P("n3 dist:", per["n3"].value_counts().sort("n3").rows())
cat=per.with_columns(pl.when(pl.col("n")==0).then(pl.lit("none")).when(pl.col("n3")==0).then(pl.lit("S2only")).when(pl.col("n2")==0).then(pl.lit("S3only")).otherwise(pl.lit("both")).alias("cat"))
P("category:", cat["cat"].value_counts().sort("cat").rows())
P("category x country:", cat.group_by("country","cat").len().sort("country","cat").rows())
P("n by country (mean, singletons):", per.group_by("country").agg(pl.col("n").mean().alias("mean"), (pl.col("n")==0).mean().alias("single"), pl.col("n").max().alias("max")).rows())
# country consistency
cm=pl.concat([s2.select("entity_id",pl.col("country").alias("mc")),s3.select("entity_id",pl.col("country").alias("mc"))])
pc=pairs.join(cm,left_on="m",right_on="entity_id").join(s1.select(pl.col("entity_id").alias("s1"),"country"),on="s1")
P("country mismatch pairs:", (pc["mc"]!=pc["country"]).sum(), " breakdown:", pc.filter(pl.col("mc")!=pl.col("country")).group_by("country","mc").len().rows())
# distractors: S2/S3 not matched by country
um=cm.join(pairs.select("m").unique(),left_on="entity_id",right_on="m",how="anti")
P("unmatched S2/S3 by country:", um.group_by("mc").len().rows(), " total unmatched:", um.height)
P("brute force comparisons S1 x (S2+S3):", s1.height*(s2.height+s3.height), " within-country:", sum(s1.filter(pl.col('country')==c).height*cm.filter(pl.col('mc')==c).height for c in ['US','India']))
P("positive rate (within country):", pairs.height/sum(s1.filter(pl.col('country')==c).height*cm.filter(pl.col('mc')==c).height for c in ['US','India']))
# leakage: id numeric correlation and row order
s1i=s1.with_row_index("r1").select(pl.col("entity_id").alias("s1"),"r1")
s2i=pl.concat([s2.with_row_index("rm").select("entity_id","rm"), s3.with_row_index("rm").select("entity_id","rm")])
L=pairs.join(s1i,on="s1").join(s2i,left_on="m",right_on="entity_id")
a=L["s1"].str.slice(3).cast(pl.Float64).to_numpy(); b=L["m"].str.slice(3).cast(pl.Float64).to_numpy()
P("corr(id s1, id match):", np.corrcoef(a,b)[0,1], " corr(row s1, row match):", np.corrcoef(L["r1"].to_numpy(),L["rm"].to_numpy())[0,1])
# within an S1, are matched S2 rows adjacent?
g=L.filter(pl.col("src")=="S2").group_by("s1").agg(pl.col("rm").max()-pl.col("rm").min(), pl.len()).filter(pl.col("len")>1)
P("S2 row-span among multi-matches (median, frac<=len):", g["rm"].median(), (g["rm"]<=g["len"]).mean())
# are S1 ids sorted in file? gt order same as S1 order?
P("gt order == s1 order:", (gt["source1_entity_id"]==s1["entity_id"]).mean())
P("s1 file sorted by id?", s1["entity_id"].is_sorted())
per.write_parquet("work/train_per_s1.parquet"); pairs.select("s1","m","src").write_parquet("work/train_pairs.parquet")
